services:
  - type: web
    name: nutrify-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm run render-build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 22.17.1
      - key: MONGO_URI
        sync: false
      - key: JWT_SIGN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
